{"uuid": "4f8c0ced-c175-41b8-9521-419fe6b1558f", "children": ["87f51ca8-c5bb-4b8e-9dac-e27552526bb1"], "befores": [{"name": "browser", "status": "passed", "start": 1607929136056, "stop": 1607929147010}], "afters": [{"name": "browser::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: Неверный ответ или закончилось время! Попробуйте запустить тест снова.\nMessage: unexpected alert open: {Alert text : Неверный ответ или закончилось время! Попробуйте запустить тест снова.}\n  (Session info: chrome=87.0.4280.88)\n\n", "trace": "  File \"c:\\users\\azakhare\\environments\\selenium_env\\lib\\site-packages\\allure_commons\\_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"c:\\users\\azakhare\\environments\\selenium_env\\lib\\site-packages\\_pytest\\fixtures.py\", line 786, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\azakhare\\PycharmProjects\\stepik_lessons\\module_5\\conftest.py\", line 42, in browser\n    browser.save_screenshot('Screenshots/screenshot-%s.png' % now)\n  File \"c:\\users\\azakhare\\environments\\selenium_env\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1043, in save_screenshot\n    return self.get_screenshot_as_file(filename)\n  File \"c:\\users\\azakhare\\environments\\selenium_env\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1020, in get_screenshot_as_file\n    png = self.get_screenshot_as_png()\n  File \"c:\\users\\azakhare\\environments\\selenium_env\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1052, in get_screenshot_as_png\n    return base64.b64decode(self.get_screenshot_as_base64().encode('ascii'))\n  File \"c:\\users\\azakhare\\environments\\selenium_env\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1062, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)['value']\n  File \"c:\\users\\azakhare\\environments\\selenium_env\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 320, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\azakhare\\environments\\selenium_env\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 241, in check_response\n    raise exception_class(message, screen, stacktrace, alert_text)\n"}, "start": 1607929150733, "stop": 1607929150737}], "start": 1607929136056, "stop": 1607929150737}