{"uuid": "8a640a45-abbd-4c99-a09b-d1974891286f", "children": ["436f9664-ea08-41da-be33-6d69231141cc"], "befores": [{"name": "browser", "status": "passed", "start": 1607929038110, "stop": 1607929048983}], "afters": [{"name": "browser::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: Неверный ответ или закончилось время! Попробуйте запустить тест снова.\nMessage: unexpected alert open: {Alert text : Неверный ответ или закончилось время! Попробуйте запустить тест снова.}\n  (Session info: chrome=87.0.4280.88)\n\n", "trace": "  File \"c:\\users\\azakhare\\environments\\selenium_env\\lib\\site-packages\\allure_commons\\_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"c:\\users\\azakhare\\environments\\selenium_env\\lib\\site-packages\\_pytest\\fixtures.py\", line 786, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\azakhare\\PycharmProjects\\stepik_lessons\\module_5\\conftest.py\", line 42, in browser\n    browser.save_screenshot('Screenshots/screenshot-%s.png' % now)\n  File \"c:\\users\\azakhare\\environments\\selenium_env\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1043, in save_screenshot\n    return self.get_screenshot_as_file(filename)\n  File \"c:\\users\\azakhare\\environments\\selenium_env\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1020, in get_screenshot_as_file\n    png = self.get_screenshot_as_png()\n  File \"c:\\users\\azakhare\\environments\\selenium_env\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1052, in get_screenshot_as_png\n    return base64.b64decode(self.get_screenshot_as_base64().encode('ascii'))\n  File \"c:\\users\\azakhare\\environments\\selenium_env\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1062, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)['value']\n  File \"c:\\users\\azakhare\\environments\\selenium_env\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 320, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\azakhare\\environments\\selenium_env\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 241, in check_response\n    raise exception_class(message, screen, stacktrace, alert_text)\n"}, "start": 1607929052773, "stop": 1607929052817}], "start": 1607929038110, "stop": 1607929052817}